log_level = "WARN"
position = "Bottom"
app_launcher_cmd = "~/.config/rofi/launcher.sh"
clipboard_cmd = "cliphist-rofi-img | wl-copy"
truncate_title_after_length = 150

[outputs]
Targets = [ "DP-2", "HDMI-A-1" ]

[modules]
left = [ "Workspaces" ]
center = [ "Updates" ]
right = [ "SystemInfo", [ "Clock", "Privacy", "Settings" ] ]

[updates]
check_cmd = "checkupdates; paru -Qua"
update_cmd = 'alacritty -e bash -c "paru; echo Done - Press enter to exit; read" &'

[workspaces]
visibility_mode = "All"
enable_workspace_filling = false

[system]
cpu_warn_threshold = 60
cpu_alert_threshold = 80
mem_warn_threshold = 70
mem_alert_threshold = 85
temp_warn_threshold = 60
temp_alert_threshold = 80

[clock]
format = "%a %d %b %R"

[media_player]
max_title_length = 100

[settings]
lock_cmd = "hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
